//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QlyNhanVienAndroid.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="severBarcodeSoap", Namespace="http://tempuri.org/")]
    public partial class severBarcode : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChecksotheOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteNhanVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertNhanvienOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNhanVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkbarcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkprdbabOperationCompleted;
        
        private System.Threading.SendOrPostCallback datetimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback mokhoabarcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback kieuloikhoaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_shiftOperationCompleted;
        
        private System.Threading.SendOrPostCallback checklidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkkhoahaychuaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public severBarcode() {
            this.Url = "http://198.1.10.232:4567/severBarcode.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChecksotheCompletedEventHandler ChecksotheCompleted;
        
        /// <remarks/>
        public event checkLoginCompletedEventHandler checkLoginCompleted;
        
        /// <remarks/>
        public event deleteNhanVienCompletedEventHandler deleteNhanVienCompleted;
        
        /// <remarks/>
        public event InsertNhanvienCompletedEventHandler InsertNhanvienCompleted;
        
        /// <remarks/>
        public event UpdateNhanVienCompletedEventHandler UpdateNhanVienCompleted;
        
        /// <remarks/>
        public event getDataCompletedEventHandler getDataCompleted;
        
        /// <remarks/>
        public event checkbarcodeCompletedEventHandler checkbarcodeCompleted;
        
        /// <remarks/>
        public event checkprdbabCompletedEventHandler checkprdbabCompleted;
        
        /// <remarks/>
        public event datetimeCompletedEventHandler datetimeCompleted;
        
        /// <remarks/>
        public event insertCompletedEventHandler insertCompleted;
        
        /// <remarks/>
        public event mokhoabarcodeCompletedEventHandler mokhoabarcodeCompleted;
        
        /// <remarks/>
        public event kieuloikhoaCompletedEventHandler kieuloikhoaCompleted;
        
        /// <remarks/>
        public event Get_shiftCompletedEventHandler Get_shiftCompleted;
        
        /// <remarks/>
        public event checklidoCompletedEventHandler checklidoCompleted;
        
        /// <remarks/>
        public event checkkhoahaychuaCompletedEventHandler checkkhoahaychuaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Checksothe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Checksothe(string empno) {
            object[] results = this.Invoke("Checksothe", new object[] {
                        empno});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ChecksotheAsync(string empno) {
            this.ChecksotheAsync(empno, null);
        }
        
        /// <remarks/>
        public void ChecksotheAsync(string empno, object userState) {
            if ((this.ChecksotheOperationCompleted == null)) {
                this.ChecksotheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChecksotheOperationCompleted);
            }
            this.InvokeAsync("Checksothe", new object[] {
                        empno}, this.ChecksotheOperationCompleted, userState);
        }
        
        private void OnChecksotheOperationCompleted(object arg) {
            if ((this.ChecksotheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChecksotheCompleted(this, new ChecksotheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] checkLogin(string ho, string ten) {
            object[] results = this.Invoke("checkLogin", new object[] {
                        ho,
                        ten});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void checkLoginAsync(string ho, string ten) {
            this.checkLoginAsync(ho, ten, null);
        }
        
        /// <remarks/>
        public void checkLoginAsync(string ho, string ten, object userState) {
            if ((this.checkLoginOperationCompleted == null)) {
                this.checkLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckLoginOperationCompleted);
            }
            this.InvokeAsync("checkLogin", new object[] {
                        ho,
                        ten}, this.checkLoginOperationCompleted, userState);
        }
        
        private void OncheckLoginOperationCompleted(object arg) {
            if ((this.checkLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkLoginCompleted(this, new checkLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteNhanVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string deleteNhanVien(string ho, string username) {
            object[] results = this.Invoke("deleteNhanVien", new object[] {
                        ho,
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteNhanVienAsync(string ho, string username) {
            this.deleteNhanVienAsync(ho, username, null);
        }
        
        /// <remarks/>
        public void deleteNhanVienAsync(string ho, string username, object userState) {
            if ((this.deleteNhanVienOperationCompleted == null)) {
                this.deleteNhanVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteNhanVienOperationCompleted);
            }
            this.InvokeAsync("deleteNhanVien", new object[] {
                        ho,
                        username}, this.deleteNhanVienOperationCompleted, userState);
        }
        
        private void OndeleteNhanVienOperationCompleted(object arg) {
            if ((this.deleteNhanVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteNhanVienCompleted(this, new deleteNhanVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNhanvien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertNhanvien(string ho, string ten) {
            object[] results = this.Invoke("InsertNhanvien", new object[] {
                        ho,
                        ten});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertNhanvienAsync(string ho, string ten) {
            this.InsertNhanvienAsync(ho, ten, null);
        }
        
        /// <remarks/>
        public void InsertNhanvienAsync(string ho, string ten, object userState) {
            if ((this.InsertNhanvienOperationCompleted == null)) {
                this.InsertNhanvienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertNhanvienOperationCompleted);
            }
            this.InvokeAsync("InsertNhanvien", new object[] {
                        ho,
                        ten}, this.InsertNhanvienOperationCompleted, userState);
        }
        
        private void OnInsertNhanvienOperationCompleted(object arg) {
            if ((this.InsertNhanvienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertNhanvienCompleted(this, new InsertNhanvienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateNhanVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateNhanVien(string hoCu, string tenCu, string hoMoi, string tenMoi) {
            object[] results = this.Invoke("UpdateNhanVien", new object[] {
                        hoCu,
                        tenCu,
                        hoMoi,
                        tenMoi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateNhanVienAsync(string hoCu, string tenCu, string hoMoi, string tenMoi) {
            this.UpdateNhanVienAsync(hoCu, tenCu, hoMoi, tenMoi, null);
        }
        
        /// <remarks/>
        public void UpdateNhanVienAsync(string hoCu, string tenCu, string hoMoi, string tenMoi, object userState) {
            if ((this.UpdateNhanVienOperationCompleted == null)) {
                this.UpdateNhanVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNhanVienOperationCompleted);
            }
            this.InvokeAsync("UpdateNhanVien", new object[] {
                        hoCu,
                        tenCu,
                        hoMoi,
                        tenMoi}, this.UpdateNhanVienOperationCompleted, userState);
        }
        
        private void OnUpdateNhanVienOperationCompleted(object arg) {
            if ((this.UpdateNhanVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNhanVienCompleted(this, new UpdateNhanVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getData() {
            object[] results = this.Invoke("getData", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void getDataAsync() {
            this.getDataAsync(null);
        }
        
        /// <remarks/>
        public void getDataAsync(object userState) {
            if ((this.getDataOperationCompleted == null)) {
                this.getDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDataOperationCompleted);
            }
            this.InvokeAsync("getData", new object[0], this.getDataOperationCompleted, userState);
        }
        
        private void OngetDataOperationCompleted(object arg) {
            if ((this.getDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDataCompleted(this, new getDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkbarcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkbarcode(string Barcode) {
            object[] results = this.Invoke("checkbarcode", new object[] {
                        Barcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkbarcodeAsync(string Barcode) {
            this.checkbarcodeAsync(Barcode, null);
        }
        
        /// <remarks/>
        public void checkbarcodeAsync(string Barcode, object userState) {
            if ((this.checkbarcodeOperationCompleted == null)) {
                this.checkbarcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckbarcodeOperationCompleted);
            }
            this.InvokeAsync("checkbarcode", new object[] {
                        Barcode}, this.checkbarcodeOperationCompleted, userState);
        }
        
        private void OncheckbarcodeOperationCompleted(object arg) {
            if ((this.checkbarcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkbarcodeCompleted(this, new checkbarcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkprdbab", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkprdbab(string barcode) {
            object[] results = this.Invoke("checkprdbab", new object[] {
                        barcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkprdbabAsync(string barcode) {
            this.checkprdbabAsync(barcode, null);
        }
        
        /// <remarks/>
        public void checkprdbabAsync(string barcode, object userState) {
            if ((this.checkprdbabOperationCompleted == null)) {
                this.checkprdbabOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckprdbabOperationCompleted);
            }
            this.InvokeAsync("checkprdbab", new object[] {
                        barcode}, this.checkprdbabOperationCompleted, userState);
        }
        
        private void OncheckprdbabOperationCompleted(object arg) {
            if ((this.checkprdbabCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkprdbabCompleted(this, new checkprdbabCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/datetime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string datetime() {
            object[] results = this.Invoke("datetime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void datetimeAsync() {
            this.datetimeAsync(null);
        }
        
        /// <remarks/>
        public void datetimeAsync(object userState) {
            if ((this.datetimeOperationCompleted == null)) {
                this.datetimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndatetimeOperationCompleted);
            }
            this.InvokeAsync("datetime", new object[0], this.datetimeOperationCompleted, userState);
        }
        
        private void OndatetimeOperationCompleted(object arg) {
            if ((this.datetimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.datetimeCompleted(this, new datetimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insert(string barcode, string sothe, string lido, string stacode) {
            object[] results = this.Invoke("insert", new object[] {
                        barcode,
                        sothe,
                        lido,
                        stacode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertAsync(string barcode, string sothe, string lido, string stacode) {
            this.insertAsync(barcode, sothe, lido, stacode, null);
        }
        
        /// <remarks/>
        public void insertAsync(string barcode, string sothe, string lido, string stacode, object userState) {
            if ((this.insertOperationCompleted == null)) {
                this.insertOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertOperationCompleted);
            }
            this.InvokeAsync("insert", new object[] {
                        barcode,
                        sothe,
                        lido,
                        stacode}, this.insertOperationCompleted, userState);
        }
        
        private void OninsertOperationCompleted(object arg) {
            if ((this.insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertCompleted(this, new insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mokhoabarcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string mokhoabarcode(string barcode, string sothe, string lido) {
            object[] results = this.Invoke("mokhoabarcode", new object[] {
                        barcode,
                        sothe,
                        lido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void mokhoabarcodeAsync(string barcode, string sothe, string lido) {
            this.mokhoabarcodeAsync(barcode, sothe, lido, null);
        }
        
        /// <remarks/>
        public void mokhoabarcodeAsync(string barcode, string sothe, string lido, object userState) {
            if ((this.mokhoabarcodeOperationCompleted == null)) {
                this.mokhoabarcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmokhoabarcodeOperationCompleted);
            }
            this.InvokeAsync("mokhoabarcode", new object[] {
                        barcode,
                        sothe,
                        lido}, this.mokhoabarcodeOperationCompleted, userState);
        }
        
        private void OnmokhoabarcodeOperationCompleted(object arg) {
            if ((this.mokhoabarcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mokhoabarcodeCompleted(this, new mokhoabarcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/kieuloikhoa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] kieuloikhoa(string lido) {
            object[] results = this.Invoke("kieuloikhoa", new object[] {
                        lido});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void kieuloikhoaAsync(string lido) {
            this.kieuloikhoaAsync(lido, null);
        }
        
        /// <remarks/>
        public void kieuloikhoaAsync(string lido, object userState) {
            if ((this.kieuloikhoaOperationCompleted == null)) {
                this.kieuloikhoaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnkieuloikhoaOperationCompleted);
            }
            this.InvokeAsync("kieuloikhoa", new object[] {
                        lido}, this.kieuloikhoaOperationCompleted, userState);
        }
        
        private void OnkieuloikhoaOperationCompleted(object arg) {
            if ((this.kieuloikhoaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.kieuloikhoaCompleted(this, new kieuloikhoaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_shift", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_shift() {
            object[] results = this.Invoke("Get_shift", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_shiftAsync() {
            this.Get_shiftAsync(null);
        }
        
        /// <remarks/>
        public void Get_shiftAsync(object userState) {
            if ((this.Get_shiftOperationCompleted == null)) {
                this.Get_shiftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_shiftOperationCompleted);
            }
            this.InvokeAsync("Get_shift", new object[0], this.Get_shiftOperationCompleted, userState);
        }
        
        private void OnGet_shiftOperationCompleted(object arg) {
            if ((this.Get_shiftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_shiftCompleted(this, new Get_shiftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checklido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] checklido(string barcode) {
            object[] results = this.Invoke("checklido", new object[] {
                        barcode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void checklidoAsync(string barcode) {
            this.checklidoAsync(barcode, null);
        }
        
        /// <remarks/>
        public void checklidoAsync(string barcode, object userState) {
            if ((this.checklidoOperationCompleted == null)) {
                this.checklidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchecklidoOperationCompleted);
            }
            this.InvokeAsync("checklido", new object[] {
                        barcode}, this.checklidoOperationCompleted, userState);
        }
        
        private void OnchecklidoOperationCompleted(object arg) {
            if ((this.checklidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checklidoCompleted(this, new checklidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkkhoahaychua", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkkhoahaychua(string barcode) {
            object[] results = this.Invoke("checkkhoahaychua", new object[] {
                        barcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkkhoahaychuaAsync(string barcode) {
            this.checkkhoahaychuaAsync(barcode, null);
        }
        
        /// <remarks/>
        public void checkkhoahaychuaAsync(string barcode, object userState) {
            if ((this.checkkhoahaychuaOperationCompleted == null)) {
                this.checkkhoahaychuaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckkhoahaychuaOperationCompleted);
            }
            this.InvokeAsync("checkkhoahaychua", new object[] {
                        barcode}, this.checkkhoahaychuaOperationCompleted, userState);
        }
        
        private void OncheckkhoahaychuaOperationCompleted(object arg) {
            if ((this.checkkhoahaychuaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkkhoahaychuaCompleted(this, new checkkhoahaychuaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ChecksotheCompletedEventHandler(object sender, ChecksotheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChecksotheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChecksotheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void checkLoginCompletedEventHandler(object sender, checkLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteNhanVienCompletedEventHandler(object sender, deleteNhanVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteNhanVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteNhanVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertNhanvienCompletedEventHandler(object sender, InsertNhanvienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertNhanvienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertNhanvienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateNhanVienCompletedEventHandler(object sender, UpdateNhanVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateNhanVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateNhanVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getDataCompletedEventHandler(object sender, getDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void checkbarcodeCompletedEventHandler(object sender, checkbarcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkbarcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkbarcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void checkprdbabCompletedEventHandler(object sender, checkprdbabCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkprdbabCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkprdbabCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void datetimeCompletedEventHandler(object sender, datetimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class datetimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal datetimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertCompletedEventHandler(object sender, insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void mokhoabarcodeCompletedEventHandler(object sender, mokhoabarcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mokhoabarcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mokhoabarcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void kieuloikhoaCompletedEventHandler(object sender, kieuloikhoaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class kieuloikhoaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal kieuloikhoaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_shiftCompletedEventHandler(object sender, Get_shiftCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_shiftCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_shiftCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void checklidoCompletedEventHandler(object sender, checklidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checklidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checklidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void checkkhoahaychuaCompletedEventHandler(object sender, checkkhoahaychuaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkkhoahaychuaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkkhoahaychuaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591